# Generated by Django 5.1.13 on 2025-12-09 17:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tasks", "0058_task_precomputed_agreement"),
    ]

    operations = [
        migrations.AddField(
            model_name="task",
            name="labeled_by_tool",
            field=models.CharField(
                blank=True,
                help_text="Name of the Tool that performed this label task",
                max_length=255,
                null=True,
            ),
        ),
    ]
