# Generated by Django 5.1.13 on 2026-01-15 07:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("tasks", "0059_task_labeled_by_tool"),
        ("tasks", "0060_add_allow_skip_to_task"),
    ]

    operations = []
