# Generated by Django 5.1.13 on 2025-11-12 15:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("projects", "0034_tool"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="tool",
            name="description",
        ),
        migrations.RemoveField(
            model_name="tool",
            name="title",
        ),
        migrations.AddField(
            model_name="tool",
            name="name",
            field=models.CharField(
                default="Unnamed", help_text="Name Tool", max_length=256
            ),
        ),
    ]
