# Generated by Django 5.1.13 on 2025-12-11 04:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tools", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="tool",
            name="color_data",
            field=models.CharField(
                blank=True,
                default="#5CA5F3",
                help_text="Color code represent Tool",
                max_length=7,
            ),
        ),
    ]
